-- MySQL Script generated by MySQL Workbench
-- mié 3 jun 2020 15:29:41 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema castielTraducciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema castielTraducciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `castielTraducciones` DEFAULT CHARACTER SET latin1 ;
USE `castielTraducciones` ;

-- -----------------------------------------------------
-- Table `castielTraducciones`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castielTraducciones`.`users` ;

CREATE TABLE IF NOT EXISTS `castielTraducciones`.`users` (
  `user_id` CHAR(36) NOT NULL,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `contact_email` TEXT NULL DEFAULT NULL,
  `contact_web` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castielTraducciones`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castielTraducciones`.`translators` ;

CREATE TABLE IF NOT EXISTS `castielTraducciones`.`translators` (
  `translator_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `details` TEXT NOT NULL,
  `category` VARCHAR(15) NOT NULL,
  `language` VARCHAR(15) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `closed_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`translator_id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `transalators_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `castielTraducciones`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `castielTraducciones` ;

-- -----------------------------------------------------
-- Placeholder table for view `castielTraducciones`.`translators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castielTraducciones`.`translators` (`translator_id` INT, `user_id` INT, `user_name` INT, `user_avatar_url` INT, `title` INT, `description` INT, `details` INT, `category` INT, `language` INT, `created_at` INT, `updated_at` INT, `closed_at` INT);

-- -----------------------------------------------------
-- View `castielTraducciones`.`translators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castielTraducciones`.`translators`;
DROP VIEW IF EXISTS `castielTraducciones`.`translators` ;
USE `castielTraducciones`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `castielTraducciones`.`translators` AS select `castielTraducciones`.`translators`.`translator_id` AS `translator_id`,`castielTraducciones`.`translators`.`user_id` AS `user_id`,`castielTraducciones`.`users`.`name` AS `user_name`,`castielTraducciones`.`users`.`avatar_url` AS `user_avatar_url`,`castielTraducciones`.`translators`.`title` AS `title`,`castielTraducciones`.`translators`.`description` AS `description`,`castielTraducciones`.`translators`.`details` AS `details`,`castielTraducciones`.`translators`.`category` AS `category`,`castielTraducciones`.`translators`.`language` AS `language`,`castielTraducciones`.`translators`.`created_at` AS `created_at`,`castielTraducciones`.`translators`.`updated_at` AS `updated_at`,`castielTraducciones`.`translators`.`closed_at` AS `closed_at`,count(`castielTraducciones`.`translator_id`) from ((`castielTraducciones`.`translators` left join `castielTraducciones` on((`castielTraducciones`.`trasnlators`.`translator_id` = `castielTraducciones`.`translator_id`))) join `castielTraducciones`.`users` on((`castielTraducciones`.`translators`.`user_id` = `castielTraducciones`.`users`.`user_id`))) group by `castielTraducciones`.`translators`.`translator_id` order by `castielTraducciones`.`translators`.`created_at` desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
